#!/bin/bash -e
target=${1:-.}

mkdir -p "$target"{,/roles,/recipes,/files}
touch "$target"/{README.md,install.sh,roles/.gitkeep,recipes/.gitkeep,files/.gitkeep}
chmod +x "$target"/install.sh
echo "compile" >> "$target"/.gitignore
